query getDocuments {
    documents {
        id
        title
        firstName
        lastName
        position
        email
        phoneNumber
        userId
        createdAt
        updatedAt
    }
}